# Generated by Django 5.0.6 on 2024-09-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webform',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
