# Generated by Django 5.0.7 on 2024-08-09 16:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('entity', models.CharField(max_length=200)),
                ('entity_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CallAndWebForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='')),
                ('metadata', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hotline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=250)),
                ('file_path', models.CharField(max_length=250)),
                ('file', models.CharField(max_length=250)),
                ('created_at', models.TimeField(verbose_name=datetime.datetime(2024, 8, 9, 16, 18, 19, 490663))),
                ('modify_at', models.TimeField(verbose_name=datetime.datetime(2024, 8, 9, 16, 18, 19, 490663))),
            ],
        ),
        migrations.CreateModel(
            name='Intial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Web Form', 'Web Form'), ('Hotline', 'Hotline'), ('Information other', 'Information other')], default='Web Form', max_length=250)),
                ('information_source', models.TextField(max_length=250)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidApp.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_information_date', models.DateField(auto_now=True)),
                ('information_other', models.TextField(max_length=250)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('modified_at', models.DateField(auto_now=True)),
                ('agency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidApp.agency')),
                ('intial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidApp.intial')),
                ('report_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReportReviewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='cidApp.agency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=200)),
                ('passport_no', models.CharField(max_length=200)),
                ('other_id', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('business_name', models.CharField(max_length=200)),
                ('business_address', models.CharField(max_length=200)),
                ('employer_name', models.CharField(max_length=200)),
                ('conveyance_description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=250)),
                ('information_source', models.CharField(choices=[('1', 'Confirmed by other Source'), ('2', 'Probably True'), ('3', 'Possible True'), ('4', 'Doubtful'), ('5', 'Improbable Not Confirmed'), ('6', 'Truth Cannot be Judge')], default='1', max_length=2)),
                ('source_evaluation', models.CharField(choices=[('A', 'Always Reliable'), ('B', 'Most Reliable'), ('C', 'Fairly Reliable'), ('D', 'Not Usual Reliable'), ('E', 'Unreliable'), ('F', 'Reliable Cannot be Judge')], default='A', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_birth', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('approx_age', models.IntegerField()),
                ('id_type', models.CharField(max_length=255)),
                ('id_number', models.CharField(max_length=255)),
                ('home_address', models.TextField()),
                ('business_name', models.CharField(max_length=255)),
                ('business_address', models.TextField()),
                ('bin_tin', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conveyance', models.CharField(max_length=255)),
                ('related_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Audits',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Records',
        ),
        migrations.DeleteModel(
            name='RecordsFiles',
        ),
        migrations.DeleteModel(
            name='RecordsRequest',
        ),
        migrations.DeleteModel(
            name='RecordsReviewed',
        ),
        migrations.DeleteModel(
            name='RecordsSource',
        ),
        migrations.DeleteModel(
            name='RecordsStatus',
        ),
        migrations.DeleteModel(
            name='References',
        ),
        migrations.DeleteModel(
            name='RequestStatus',
        ),
        migrations.DeleteModel(
            name='RolesPermissions',
        ),
        migrations.DeleteModel(
            name='SourceMetadata',
        ),
        migrations.DeleteModel(
            name='Subjects',
        ),
        migrations.DeleteModel(
            name='Texts',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.DeleteModel(
            name='UsersRoles',
        ),
        migrations.AddField(
            model_name='callandwebform',
            name='hotline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidApp.hotline'),
        ),
        migrations.AddField(
            model_name='report',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidApp.callandwebform'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidApp.report'),
        ),
        migrations.AddField(
            model_name='reportreviewed',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidApp.report'),
        ),
        migrations.AddField(
            model_name='callandwebform',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidApp.status'),
        ),
        migrations.AddField(
            model_name='report',
            name='Subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cidApp.subject'),
        ),
        migrations.AddField(
            model_name='text',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cidApp.report'),
        ),
        migrations.AddField(
            model_name='text',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='callandwebform',
            name='webform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidApp.webform'),
        ),
    ]
