# Generated by Django 5.0.7 on 2024-08-09 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0002_agency_audit_callandwebform_comment_file_hotline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotline',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 9, 16, 19, 13, 210980)),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='modify_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 9, 16, 19, 13, 210980)),
        ),
    ]
