# Generated by Django 5.0.6 on 2024-09-06 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0002_alter_webform_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='webform',
            name='ligar',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
