# Generated by Django 5.0.6 on 2024-09-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0004_rename_an_email_subject_bin_tin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='pob',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
