# Generated by Django 5.0.7 on 2024-08-12 10:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0006_rename_text_textattach_alter_hotline_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file_attached',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidApp.fileattch'),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 12, 10, 47, 13, 141817)),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='modify_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 12, 10, 47, 13, 141817)),
        ),
    ]
