# Generated by Django 5.0.6 on 2024-09-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0006_subject_busaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotline',
            name='origin_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
