# Generated by Django 5.0.7 on 2024-08-12 11:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0007_report_file_attached_alter_hotline_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattch',
            name='path',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 12, 11, 1, 26, 310056)),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='modify_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 12, 11, 1, 26, 310056)),
        ),
        migrations.AlterField(
            model_name='textattach',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidApp.report'),
        ),
    ]
