# Generated by Django 5.0.7 on 2024-08-12 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0008_alter_fileattch_path_alter_hotline_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='intial',
            new_name='initial',
        ),
        migrations.AlterField(
            model_name='hotline',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 12, 11, 53, 20, 468812)),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='modify_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 12, 11, 53, 20, 468812)),
        ),
    ]
