# Generated by Django 5.0.7 on 2024-08-12 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0009_rename_intial_report_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Completed', 'Completed')], default='Incomplete', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 12, 17, 9, 45, 380666)),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='modify_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 12, 17, 9, 45, 380666)),
        ),
        migrations.AlterField(
            model_name='intial',
            name='information_source',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
