# Generated by Django 5.0.7 on 2024-08-13 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0011_nationality_remove_subject_employer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotline',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 13, 9, 43, 20, 425593)),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='modify_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 13, 9, 43, 20, 425593)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='conveyance_description',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
