# Generated by Django 5.0.7 on 2024-08-14 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0013_rename_comment_comments_alter_hotline_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotline',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 14, 14, 17, 44, 213861)),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='modify_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 14, 14, 17, 44, 213861)),
        ),
        migrations.AlterField(
            model_name='subject',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
