# Generated by Django 5.0.7 on 2024-08-15 08:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0014_alter_hotline_created_at_alter_hotline_modify_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cidApp.report'),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 15, 8, 51, 14, 410746)),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='modify_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 15, 8, 51, 14, 410746)),
        ),
    ]
