# Generated by Django 5.0.7 on 2024-08-15 14:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0015_alter_comments_report_alter_hotline_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotline',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 15, 14, 13, 29, 726345)),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='modify_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 8, 15, 14, 13, 29, 726345)),
        ),
        migrations.AlterField(
            model_name='textattach',
            name='information_source',
            field=models.CharField(choices=[('1', 'Confirmed by other Source'), ('2', 'Probably True'), ('3', 'Possible True'), ('4', 'Doubtful'), ('5', 'Improbable Not Confirmed'), ('6', 'Truth Cannot be Judge')], default='1', max_length=250),
        ),
        migrations.AlterField(
            model_name='textattach',
            name='source_evaluation',
            field=models.CharField(choices=[('A', 'Always Reliable'), ('B', 'Most Reliable'), ('C', 'Fairly Reliable'), ('D', 'Not Usual Reliable'), ('E', 'Unreliable'), ('F', 'Reliable Cannot be Judge')], default='A', max_length=250),
        ),
    ]
