# Generated by Django 5.0.6 on 2024-09-03 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cidApp', '0017_reportreviewed_confirm_reportreviewed_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotline',
            name='created_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 9, 3, 8, 40, 27, 24295)),
        ),
        migrations.AlterField(
            model_name='hotline',
            name='modify_at',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 9, 3, 8, 40, 27, 24311)),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('Incomplete', 'Incomplete'), ('Completed', 'Completed'), ('Closed', 'Closed'), ('Disseminate', 'Disseminate'), ('Archived', 'Archived')], default='Incomplete', max_length=20),
        ),
    ]
